source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ConnectSwift_Example', :exclusive => true do
  pod "ConnectSwift", :path => "../"
end

target 'ConnectSwift_Tests', :exclusive => true do
  pod "ConnectSwift", :path => "../"

  
end
